from django.db import models
from django.conf import settings
# Create your models here.
class Mast(models.Model):
	client = models.ForeignKey(to=settings.AUTH_USER_MODEL,null=True, blank=True, on_delete=models.CASCADE)
	q1 = models.BooleanField(null=False, blank=False, required=False)
	q2 = models.BooleanField(null=False, blank=False, required=False)
	q3 = models.BooleanField(null=False, blank=False, required=False)
	q4 = models.BooleanField(null=False, blank=False, required=False)
	q5 = models.BooleanField(null=False, blank=False, required=False)
	q6 = models.BooleanField(null=False, blank=False, required=False)
	q7 = models.BooleanField(null=False, blank=False, required=False)
	q8 = models.BooleanField(null=False, blank=False, required=False)
	q9 = models.BooleanField(null=False, blank=False, required=False)
	q10 = models.BooleanField(null=False, blank=False, required=False)
	q11 = models.BooleanField(null=False, blank=False, required=False)
	q12 = models.BooleanField(null=False, blank=False, required=False)
	q12 = models.BooleanField(null=False, blank=False, required=False)
	q13 = models.BooleanField(null=False, blank=False, required=False)
	q14 = models.BooleanField(null=False, blank=False, required=False)
	q15 = models.BooleanField(null=False, blank=False, required=False)
	q16 = models.BooleanField(null=False, blank=False, required=False)
	q17 = models.BooleanField(null=False, blank=False, required=False)
	q18 = models.BooleanField(null=False, blank=False, required=False)
	q19 = models.BooleanField(null=False, blank=False, required=False)
	q20 = models.BooleanField(null=False, blank=False, required=False)
	q21 = models.BooleanField(null=False, blank=False, required=False)
	q21Yes = models.IntegerField(null=False, blank=False)
	q22 = models.BooleanField(null=False, blank=False, required=False)
	q22Yes = models.IntegerField(null=False, blank=False)
	mastScore = models.IntegerField(null=False, blank=False )

class Profile(models.Model):
	client = models.ForeignKey(to=settings.AUTH_USER_MODEL,null=True, blank=True, on_delete=models.CASCADE)
	streetAddress = models.CharField(null=False, blank=False, max_length=100, min_length=5)
	streetAddress2 = models.CharField(null=True, blank=True)
	city = models.CharField(null=False, blank=False, max_length=100)
	zipCode = models.CharField(null=False,blank=False, min_length=5)
	state = models.CharField(null=False, blank=False, max_length=2, min_length=2)
	primePhone = models.CharField(null=False,blank=False, max_length=10, min_length=10)
	workPhone = models.CharField(null=True,blank=True, max_length=10, min_length=10)
	dob = models.DateField(null=False, blank=True, input_formats=['%m/%d/%Y'])
	idType = models.CharField(blank=False, null=False, max_length=14)
	ethnicity = models.CharField(blank=False, null=False)
	gender = models.CharField(null=False, blank=False, max_length=6, min_length=4)
	martial = models.CharField(null=False, blank=False, max_length=9, min_length=6)
	emp = models.CharField(null=False, blank=False, max_length=18, min_length=5)
	emergencyContact = models.CharField(null=False, blank=False, max_length=50, min_length=2)
	emergencyRelationship models.CharField(null=False, blank=False, max_length=20, min_length=3)
	emergencyPhone = models.CharField(null=False, blank=False, max_length=10, min_length=10)
	emergencyEmail = models.EmailField(blank=False, null=False, max_length=150),
	income = models.CharField(max_length=10, blank=True, null=True)
	idNumber = models.CharField(blank=False, null=False, max_length=50)
	collegeGrad = models.CharField(blank=True, null=True, max_length=3)
	hsGrad = models.CharField(blank=True, null=True, max_length=3)
	interpreter = models.CharField(blank=True, null=True, max_length=3)
	edLevel = models.CharField(blank=True, null=True, max_length=150)
	familySize = models.CharField(blank=True, null=True, max_length=3)
	occupation = models.CharField(blank=True, null=True, max_length=100)
