# Generated by Django 2.0.5 on 2018-07-06 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField()),
                ('q2', models.BooleanField()),
                ('q3', models.BooleanField()),
                ('q4', models.BooleanField()),
                ('q5', models.BooleanField()),
                ('q6', models.BooleanField()),
                ('q7', models.BooleanField()),
                ('q8', models.BooleanField()),
                ('q9', models.BooleanField()),
                ('q10', models.BooleanField()),
                ('q11', models.BooleanField()),
                ('q12', models.BooleanField()),
                ('q13', models.BooleanField()),
                ('q14', models.BooleanField()),
                ('q15', models.BooleanField()),
                ('q16', models.BooleanField()),
                ('q17', models.BooleanField()),
                ('q18', models.BooleanField()),
                ('q19', models.BooleanField()),
                ('q20', models.BooleanField()),
                ('q21', models.BooleanField()),
                ('q21Yes', models.IntegerField(blank=True, null=True)),
                ('q22', models.BooleanField()),
                ('q22Yes', models.IntegerField(blank=True, null=True)),
                ('mastScore', models.IntegerField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAddress', models.CharField(max_length=100)),
                ('streetAddress2', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=2)),
                ('primePhone', models.CharField(max_length=10)),
                ('workPhone', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True)),
                ('idType', models.CharField(max_length=14)),
                ('ethnicity', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('martial', models.CharField(max_length=9)),
                ('emp', models.CharField(max_length=18)),
                ('emergencyContact', models.CharField(max_length=50)),
                ('emergencyRelationship', models.CharField(max_length=20)),
                ('emergencyPhone', models.CharField(max_length=10)),
                ('emergencyEmail', models.EmailField(max_length=150)),
                ('income', models.CharField(blank=True, max_length=10, null=True)),
                ('idNumber', models.CharField(max_length=50)),
                ('hsGrad', models.CharField(blank=True, max_length=3, null=True)),
                ('interpreter', models.CharField(blank=True, max_length=3, null=True)),
                ('edLevel', models.CharField(blank=True, max_length=150, null=True)),
                ('familySize', models.CharField(blank=True, max_length=3, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('collegeGrad', models.CharField(blank=True, max_length=3, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
