# Generated by Django 2.0.5 on 2018-09-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_psychsoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychsoc',
            name='preAmount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='psychsoc',
            name='preFirst',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='psychsoc',
            name='preFreq',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='psychsoc',
            name='preLast',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='psychsoc',
            name='su12',
            field=models.BooleanField(default=False),
        ),
    ]
