# Generated by Django 2.0.5 on 2018-09-21 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consul', '0007_course_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_psychsoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_date', models.DateField()),
                ('signup_date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consul.Course')),
            ],
        ),
    ]
