# Generated by Django 2.0.5 on 2018-10-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180902_1910'),
        ('clients', '0003_classesclient'),
    ]

    operations = [
    ]
