# Generated by Django 2.0.5 on 2019-02-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_merge_20181001_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='mast',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psychsoc',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
