# Generated by Django 2.0.5 on 2019-02-14 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0006_cage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmTruth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.BooleanField()),
                ('phi', models.BooleanField()),
                ('release_health_info', models.BooleanField()),
                ('screening_consent', models.BooleanField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
