# Generated by Django 2.0.5 on 2019-02-14 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0008_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionI_1', models.BooleanField()),
                ('sectionI_2', models.BooleanField()),
                ('sectionI_3', models.BooleanField()),
                ('sectionI_4', models.BooleanField()),
                ('sectionI_5', models.BooleanField()),
                ('sectionI_6', models.BooleanField()),
                ('sectionI_7', models.BooleanField()),
                ('sectionI_8', models.BooleanField()),
                ('sectionI_9', models.BooleanField()),
                ('sectionI_10', models.BooleanField()),
                ('sectionI_11', models.BooleanField()),
                ('sectionI_12', models.BooleanField()),
                ('sectionI_13', models.BooleanField()),
                ('sectionI_14', models.BooleanField()),
                ('sectionI_15', models.BooleanField()),
                ('sectionII_1', models.BooleanField()),
                ('sectionII_2', models.BooleanField()),
                ('sectionII_3', models.BooleanField()),
                ('sectionII_4', models.BooleanField()),
                ('sectionII_5', models.BooleanField()),
                ('sectionII_6', models.BooleanField()),
                ('sectionII_7', models.BooleanField()),
                ('sectionII_8', models.BooleanField()),
                ('sectionII_9', models.BooleanField()),
                ('sectionII_10', models.BooleanField()),
                ('sectionII_11', models.BooleanField()),
                ('sectionII_12', models.BooleanField()),
                ('sectionII_13', models.BooleanField()),
                ('sectionII_14', models.BooleanField()),
                ('sectionII_15', models.BooleanField()),
                ('reviewed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cage',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confirmtruth',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
