# Generated by Django 2.0.5 on 2018-07-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180709_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jwt_secret',
        ),
    ]
