# Generated by Django 2.0.5 on 2019-02-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pos',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
