# Generated by Django 2.0.5 on 2018-07-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consul', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='counselor1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consul.Counselor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='counselor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor2', to='consul.Counselor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='counselor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor3', to='consul.Counselor'),
        ),
    ]
