# Generated by Django 2.0.5 on 2018-07-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consul', '0003_auto_20180707_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselor',
            old_name='client',
            new_name='user',
        ),
    ]
