# Generated by Django 2.0.5 on 2018-07-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consul', '0004_auto_20180710_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='endTIme',
            new_name='endTime',
        ),
    ]
