# Generated by Django 2.0.5 on 2018-07-10 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consul', '0005_auto_20180710_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consul.Counselor')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='counselor1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='counselor2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='counselor3',
        ),
        migrations.AddField(
            model_name='counselorcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consul.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='counselors',
            field=models.ManyToManyField(through='consul.CounselorCourse', to='consul.Counselor'),
        ),
    ]
