# Generated by Django 2.0.5 on 2018-07-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consul', '0006_auto_20180710_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Drugs', max_length=100),
            preserve_default=False,
        ),
    ]
