# Generated by Django 2.0.5 on 2018-08-26 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consul', '0007_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=10)),
                ('q1', models.BooleanField()),
                ('dui', models.CharField(max_length=10)),
                ('famCounseling', models.CharField(max_length=10)),
                ('domViolence', models.CharField(max_length=10)),
                ('empAssistance', models.CharField(max_length=10)),
                ('partnership', models.CharField(max_length=10)),
                ('teenHelp', models.CharField(max_length=10)),
                ('athCounseling', models.CharField(max_length=10)),
                ('submitted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
