# Generated by Django 2.0.5 on 2018-08-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consul', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='athCounseling',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='domViolence',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dui',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='empAssistance',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='famCounseling',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='partnership',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='teenHelp',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
