# Generated by Django 2.0.5 on 2018-08-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consul', '0009_auto_20180827_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=25),
        ),
    ]
