# Generated by Django 2.0.5 on 2018-08-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consul', '0010_auto_20180827_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='q1',
            field=models.CharField(max_length=5),
        ),
    ]
