# Generated by Django 2.0.5 on 2018-12-09 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consul', '0012_auto_20180827_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorcourse',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
